

// GPIO

#define GPIO_PA_BASE 0x40006000
#define GPIO_PB_BASE 0x40006024
#define GPIO_PC_BASE 0x40006048


#define GPIO_PC_CTRL     GPIO_PC_BASE + 0x00
#define GPIO_PC_MODEL    GPIO_PC_BASE + 0x04
#define GPIO_PC_MODEH    GPIO_PC_BASE + 0x08
#define GPIO_PC_DOUT     GPIO_PC_BASE + 0x0c
#define GPIO_PC_DOUTSET  GPIO_PC_BASE + 0x10
#define GPIO_PC_DOUTCLR  GPIO_PC_BASE + 0x14
#define GPIO_PC_DOUTTGL  GPIO_PC_BASE + 0x18
#define GPIO_PC_DIN      GPIO_PC_BASE + 0x1c
#define GPIO_PC_PINLOCKN GPIO_PC_BASE + 0x20

#define GPIO_EXTIPSELL GPIO_PA_BASE + 0x100
#define GPIO_EXTIPSELH GPIO_PA_BASE + 0x104
#define GPIO_EXTIRISE  GPIO_PA_BASE + 0x108
#define GPIO_EXTIFALL  GPIO_PA_BASE + 0x10c
#define GPIO_IEN       GPIO_PA_BASE + 0x110
#define GPIO_IFC       GPIO_PA_BASE + 0x11c




